"""add availability overrides

Revision ID: 809c316dd009
Revises: 3197da49fe8e
Create Date: 2026-01-30 22:51:30.685013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809c316dd009'
down_revision = '3197da49fe8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability_overrides')
    # ### end Alembic commands ###
